tracker_type: botsort

# Association et conservation des pistes pendant les occlusions.
track_high_thresh: 0.3
track_low_thresh: 0.05
new_track_thresh: 0.3
track_buffer: 90
match_thresh: 0.8
fuse_score: True

# Re-identification native BoT-SORT.
with_reid: True
model: yolo11n-cls.pt
proximity_thresh: 0.5
appearance_thresh: 0.25

# Caméra fixe.
gmc_method: none
